server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poker?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: ct123!@#
secret:
  auth:
    jwt-secret: "123456789"
#redis:
#  config:
#    - names: user
#      endPoints: localhost:6379